version: '2'
services:
  github-service:
    image: arczipt/github-service:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    env_file:
      - redis.env
      - github.env
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    env_file:
      - redis.env